name: Build

on: push

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ${{ matrix.imageName }}
    strategy:
      matrix:
        imageName: [windows-latest, macos-10.15, ubuntu-latest]
        include:
          - imageName: windows-latest
            jobArchName: "Windows"
            agentArch: "windows"
            artifactPrefix: "windows."
            artifactSuffix: ""
            netbuilder: 'core'
            lualibs: 'prebuilt'
            loveURL: 'https://github.com/love2d/love/releases/download/11.3/love-11.3-win32.zip'
            loveZIP: 'love.zip'
            loveTAR: ''
            loveBinaryDirectory: ''
            loveResourcesDirectory: ''
            loveBinary: 'love.exe'
            jobArchName: 'macOS'
          - imageName: macos-10.15
            jobArchName: "macOS"
            agentArch: "macOS"
            artifactPrefix: "macos."
            artifactSuffix: ""
          - imageName: ubuntu-latest
            jobArchName: "linux"
            agentArch: "linux"
            artifactPrefix: "linux."
            artifactSuffix: ""

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 3

      - run: |
          echo ${{ matrix.jobArchName }}
