name: Build

on: push

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ${{ matrix.imageName }}
    strategy:
      matrix:
        imageName: [Windows, macOS, linux]

    steps:
      - uses: actions/checkout@v3
        submodules: "recursive"
        fetch-depth: 3

      - name:
